missing ',' :)
- hardware/libhardware/include/hardware/hwcomposer_defs.h:193:37: error: missing ',' between enumerators
      HWC_IS_CURSOR_LAYER = 0x00000002
                                    ^
                                    ,
- 1 error generated.
- 11:27:36 ninja failed with: exit status 1

- #### failed to build some targets (12:24 (mm:ss)) ####